name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        rm -f package-lock.json
        npm install
      
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    - name: Create 404.html for SPA routing
      working-directory: ./frontend
      run: |
        # attempting to build 404.html with redirect script
        cat > build/404.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <title>QuizCanvas - Redirecting...</title>
            <script type="text/javascript">
              // Single Page Apps for GitHub Pages
              // https://github.com/rafgraph/spa-github-pages
              var pathSegmentsToKeep = 0;
              var l = window.location;
              l.replace(
                l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
                l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                l.hash
              );
            </script>
          </head>
          <body>
            <div>Redirecting to QuizCanvas...</div>
          </body>
        </html>
        EOF
        echo "404.html created successfully"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build